<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pradja.Domain\Pradja.Domain.csproj" />
    <ProjectReference Include="..\Pradja.Migrations\Pradja.Migrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Cells" Version="24.12.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="EPPlus" Version="7.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
  </ItemGroup>

</Project>
